---
- name: Ensure aoe2-groups-proxy namespace exists
  kubernetes.core.k8s:
    name: aoe2-groups-proxy
    api_version: v1
    kind: Namespace
    state: present

- name: Apply aoe2-groups-proxy secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: aoe2-groups-proxy-secrets
        namespace: aoe2-groups-proxy
      type: Opaque
      stringData:
        service-account.json: "{{ lookup('file', 'service-account.json') | string }}"
        sheet-ids.toml: "{{ lookup('file', 'sheet-ids.toml') | string }}"
  no_log: true
