---
- name: Ensure aoe2-tournament-bot namespace exists
  kubernetes.core.k8s:
    name: aoe2-tournament-bot
    api_version: v1
    kind: Namespace
    state: present

- name: Apply aoe2-tournament-bot secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: aoe2-tournament-bot-secrets
        namespace: aoe2-tournament-bot
      type: Opaque
      stringData:
        config.toml: "{{ lookup('file', 'config.toml') | string }}"
        service-account.json: "{{ lookup('file', 'service-account.json') | string }}"
  no_log: true
