---
- name: Template demo manifest
  ansible.builtin.template:
    src: demo.yaml.j2
    dest: /etc/rancher/k3s/apps-demo.yaml
    mode: '0644'

- name: Apply demo manifest
  ansible.builtin.command: k3s kubectl apply -f /etc/rancher/k3s/apps-demo.yaml
  register: apps_demo_apply
  changed_when: apps_demo_apply.stdout is search('(created|configured)')
