apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aoe2-groups-proxy/overlays/staging
  - aoe2-groups-proxy/overlays/production
  - aoe2-tournament-bot
  - auth
  - monitoring
