---
- name: Install podman
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: true

- name: Enable podman auto-update timer
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    enabled: true
    state: started
