---
- name: Install caddy keyring
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /usr/share/keyrings/caddy-stable-archive-keyring.asc
    mode: '0644'

- name: Add caddy apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    filename: caddy-stable
    state: present

- name: Install caddy
  ansible.builtin.apt:
    name: caddy
    state: present
    update_cache: true

- name: Create caddy sites directory
  ansible.builtin.file:
    path: /etc/caddy/sites
    state: directory
    mode: '0755'

- name: Deploy base Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: '0644'
  notify: Reload caddy
