---
- name: Ensure namespaces for ghcr-pull-secret exist
  kubernetes.core.k8s:
    name: "{{ item }}"
    api_version: v1
    kind: Namespace
    state: present
  loop: "{{ ghcr_pull_secret_namespaces }}"

- name: Apply GHCR pull secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ghcr-pull-secret
        namespace: "{{ item }}"
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: >-
          {{ {'auths': {'ghcr.io': {'username': ghcr_pull_username, 'password': ghcr_pull_token,
          'auth': (ghcr_pull_username ~ ':' ~ ghcr_pull_token) | b64encode}}} | to_json }}
  loop: "{{ ghcr_pull_secret_namespaces }}"
  no_log: true
